Models/Medicine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project_AutoSuggestion_E_AppointmentApp.Models
{
    public class Medicine
    {
        [Key]
        public int MedicineId { get; set; }
        [Required(ErrorMessage = "Enter medicine name")]
        [Display(Name = "Medicine Name")]
        public string MedicineName { get; set; }

        [Required(ErrorMessage = "Enter medicine description")]
        [Display(Name = "Medicine Description")]
        [DataType(DataType.MultilineText)]
        public string MedicineDescription { get; set; }
        [Required(ErrorMessage = "Enter medicine type")]
        [Display(Name = "Medicine type")]
        public string MedicineType { get; set; }
        [Required(ErrorMessage = "Enter medicine rate")]
        [Display(Name = "Medicine Rate")]
        public string MedicineRate { get; set; }


    }
   
}

Controllers/MedicineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project_AutoSuggestion_E_AppointmentApp.Models;

namespace Project_AutoSuggestion_E_AppointmentApp.Controllers
{
    public class MedicineController:Controller
    {
       private  AppContext db=new AppContext();

        public ActionResult Index()
        {
            
         
            return View(db.MedicinEntries.ToList());
        }


        [HttpGet]
        public ActionResult Create()
        {

            return View();


        }

        [HttpPost]
        public ActionResult Create(Medicine aMedicine)
        {
      
            if (ModelState.IsValid)
            {
                if (aMedicine!=null)
                {
                    db.MedicinEntries.Add(aMedicine);
                    db.SaveChanges();
                    return RedirectToAction("Create");

                }
                
            }
            return RedirectToAction("Create");
        }
    }
}

Views/Medicine/Create.cshtml
@model Project_AutoSuggestion_E_AppointmentApp.Models.Medicine

@{
    ViewBag.Title = "Medicine Entry";
}

<h2>Enter Medicine Information</h2>



@using (Html.BeginForm("Create","Medicine",null,FormMethod.Post,new{enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.MedicineName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MedicineName)
                @Html.ValidationMessageFor(model => model.MedicineName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MedicineDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MedicineDescription)
                @Html.ValidationMessageFor(model => model.MedicineDescription)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MedicineType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MedicineType)
                @Html.ValidationMessageFor(model => model.MedicineType)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MedicineRate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MedicineRate)
                @Html.ValidationMessageFor(model => model.MedicineRate)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    @*@{
    <h1>ViewBag.Error="Medicine is succesfully added!"</h1>
}*@


@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Medicine/Index.cshtml
@model IEnumerable<Project_AutoSuggestion_E_AppointmentApp.Models.Medicine>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MedicineName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicineDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicineType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicineRate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MedicineName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MedicineDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MedicineType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MedicineRate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MedicineId }) |
            @Html.ActionLink("Details", "Details", new { id=item.MedicineId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MedicineId })
        </td>
    </tr>
}

</table>